/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const EnumContentType: typeof import('../src/utils/useEnum')['EnumContentType']
  const EnumDataType: typeof import('../src/utils/useEnum')['EnumDataType']
  const REGEXP_CODE_FOUR: typeof import('../src/utils/useRegexp')['REGEXP_CODE_FOUR']
  const REGEXP_CODE_SIX: typeof import('../src/utils/useRegexp')['REGEXP_CODE_SIX']
  const REGEXP_EMAIL: typeof import('../src/utils/useRegexp')['REGEXP_EMAIL']
  const REGEXP_PHONE: typeof import('../src/utils/useRegexp')['REGEXP_PHONE']
  const REGEXP_PWD: typeof import('../src/utils/useRegexp')['REGEXP_PWD']
  const REGEXP_URL: typeof import('../src/utils/useRegexp')['REGEXP_URL']
  const clearLocal: typeof import('../src/utils/useStorage')['clearLocal']
  const decrypto: typeof import('../src/utils/useCrypto')['decrypto']
  const encrypto: typeof import('../src/utils/useCrypto')['encrypto']
  const formatJsonToUrlParams: typeof import('../src/utils/useFormat')['formatJsonToUrlParams']
  const get: typeof import('../src/utils/useHttp')['get']
  const getLocal: typeof import('../src/utils/useStorage')['getLocal']
  const http: typeof import('../src/utils/useHttp')['http']
  const isArray: typeof import('../src/utils/useTypeOf')['isArray']
  const isBoolean: typeof import('../src/utils/useTypeOf')['isBoolean']
  const isDate: typeof import('../src/utils/useTypeOf')['isDate']
  const isFile: typeof import('../src/utils/useTypeOf')['isFile']
  const isFunction: typeof import('../src/utils/useTypeOf')['isFunction']
  const isMap: typeof import('../src/utils/useTypeOf')['isMap']
  const isNull: typeof import('../src/utils/useTypeOf')['isNull']
  const isNumber: typeof import('../src/utils/useTypeOf')['isNumber']
  const isObject: typeof import('../src/utils/useTypeOf')['isObject']
  const isRegExp: typeof import('../src/utils/useTypeOf')['isRegExp']
  const isSet: typeof import('../src/utils/useTypeOf')['isSet']
  const isString: typeof import('../src/utils/useTypeOf')['isString']
  const isUndefined: typeof import('../src/utils/useTypeOf')['isUndefined']
  const post: typeof import('../src/utils/useHttp')['post']
  const removeLocal: typeof import('../src/utils/useStorage')['removeLocal']
  const setLocal: typeof import('../src/utils/useStorage')['setLocal']
  const useFormat: typeof import('../src/utils/useFormat')['default']
}
